Repository ripe-tech/ripe-sdk-components-react, pull requests merged in 2020-11, with the labels that each got.

#25 Fixes for @babel/eslint-parser package
  .eslintrc.js
  package.json
Labels: back-port 🔮, enhancement

#26 Optional config backport
  react/components/organisms/ripe-configurator/ripe-configurator.js
  react/components/organisms/ripe-image/ripe-image.js
  react/components/organisms/ripe-price/ripe-price.js
  react/mixins/logic.js
Labels: enhancement

#27 Fix vercel deployment
  package.json
Labels: bug

#28 Update docs with recent changes
  doc/overview.md
  react/components/organisms/ripe-configurator/ripe-configurator.js
  react/components/organisms/ripe-image/ripe-image.js
  react/components/organisms/ripe-price/ripe-price.js
Labels: documentation, enhancement

#23 #26: Image component with Zoom
  doc/overview.md
  react/components/organisms/index.js
  react/components/organisms/ripe-image-zoom/index.js
  react/components/organisms/ripe-image-zoom/ripe-image-zoom.css
  react/components/organisms/ripe-image-zoom/ripe-image-zoom.js
  react/components/organisms/ripe-image-zoom/ripe-image-zoom.stories.js
  react/components/organisms/ripe-image/ripe-image.css
  react/components/organisms/ripe-image/ripe-image.js
  react/test/components/ripe-image-zoom/ripe-image-zoom.test.js
  res/images/image-zoom.png
Labels: enhancement
