Repository ripe-tech/ripe-sdk-components-react, pull requests merged in 2020-08, with the labels that each got.

#11 #2: Configurator Component Enhanced
  README.md
  react/components/organisms/ripe-configurator/ripe-configurator.js
  react/components/organisms/ripe-configurator/ripe-configurator.stories.js
  res/images/configurator-sensitivity.gif
Labels: documentation, enhancement, unit-testing

#12 #5: Price Component
  README.md
  package.json
  react/components/organisms/index.js
  react/components/organisms/ripe-price/index.js
  react/components/organisms/ripe-price/ripe-price.js
  react/components/organisms/ripe-price/ripe-price.stories.js
  react/mixins/index.js
  react/mixins/money.js
  react/test/components/ripe-price/ripe-price.test.js
  res/images/price-complex-eur.png
  res/images/price-complex-usd.png
  res/images/price.png
Labels: documentation, enhancement, unit-testing

#13 #1: Image Component Enhanced
  README.md
  react/components/organisms/ripe-image/ripe-image.js
  react/components/organisms/ripe-image/ripe-image.stories.js
  res/images/image-personalization.png
Labels: documentation, enhancement, unit-testing

#18 Fix unit tests by not loading CSS
  package.json
  react/test/webpack.config.js
Labels: bug

#17 Parts bidirectionality and refactor
  README.md
  react/components/organisms/ripe-configurator/ripe-configurator.js
  react/components/organisms/ripe-image/ripe-image.js
  react/components/organisms/ripe-price/ripe-price.js
  react/mixins/index.js
  react/mixins/logic.js
Labels: enhancement, fast-track

#16 Add Styleguidist for docs
  .github/workflows/main.yml
  .storybook/manager-head.html
  README.md
  package.json
  styleguide.config.js
  vercel.json
Labels: enhancement
